# Language
language: python
python:
  - '3.7'
# Install dependencies
install:
  - pip3 install cython
  - pip3 install -r requirements.txt
  - pip3 install pytest-cov
  - pip3 install coveralls
  - python setup.py install
# Install ffmpeg and run the tests
script:
  - sudo apt-get install ffmpeg -y
  - coverage run -m pytest
  - coverage report -m
after_success:
  - coveralls